/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package hotel;


import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;


/**
 * Main class for the Cookbook application.
 */
public class App extends Application {

  /**
     * Starts the JavaFX application.
     *
     * @param primaryStage the primary stage for this application
     */
  @Override
    public void start(Stage primaryStage) {
    try {
      FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/fxml/StartPage.fxml"));
      Parent root = fxmlLoader.load();
      Scene scene = new Scene(root);

      primaryStage.setTitle("test-Window");
      primaryStage.setScene(scene);
      primaryStage.setResizable(false);
      primaryStage.show();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  /**
     * Main method.
     *
     * @param args command line arguments
     */
  public static void main(String[] args) {
    launch(args);
  }
}


